-- Cars table for car_rental_db database
CREATE TABLE cars (
    id SERIAL PRIMARY KEY,
    city_mpg INT,
    class TEXT,
    combination_mpg INT,
    cylinders INT,
    displacement DECIMAL(3,1),
    drive TEXT,
    fuel_type TEXT,
    highway_mpg INT,
    make TEXT,
    model TEXT,
    transmission TEXT,
    year INT,
    img_path TEXT,
    car_location TEXT
);

INSERT INTO cars (
    city_mpg, class, combination_mpg, cylinders, displacement, drive,
    fuel_type, highway_mpg, make, model, transmission, year, img_path, car_location
) VALUES
(18, 'midsize car', 21, 4, 2.2, 'fwd', 'gas', 26, 'toyota', 'camry', 'a', 1993, 'https://cdn.imagin.studio/getImage?make=toyota&modelFamily=camry&year=1993&angle=front', 'Copenhagen'),
(27, 'compact car', 30, 4, 1.8, 'fwd', 'gas', 36, 'honda', 'civic', 'm', 2018, 'https://cdn.imagin.studio/getImage?make=honda&modelFamily=civic&year=2018&angle=front', 'Aarhus'),
(23, 'suv', 26, 4, 2.5, 'awd', 'gas', 31, 'toyota', 'rav4', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=toyota&modelFamily=rav4&year=2020&angle=front', 'Odense'),
(21, 'pickup truck', 24, 6, 3.3, 'rwd', 'gas', 28, 'ford', 'f-150', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=ford&modelFamily=f-150&year=2019&angle=front', 'Copenhagen'),
(30, 'compact car', 33, 4, 2.0, 'fwd', 'gas', 40, 'mazda', 'mazda3', 'm', 2021, 'https://cdn.imagin.studio/getImage?make=mazda&modelFamily=mazda3&year=2021&angle=front', 'Aarhus'),
(22, 'luxury suv', 25, 6, 3.0, 'awd', 'gas', 29, 'bmw', 'x5', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=bmw&modelFamily=x5&year=2020&angle=front', 'Odense'),
(28, 'hatchback', 32, 4, 1.6, 'fwd', 'gas', 38, 'hyundai', 'elantra', 'a', 2017, 'https://cdn.imagin.studio/getImage?make=hyundai&modelFamily=elantra&year=2017&angle=front', 'Copenhagen'),
(24, 'sedan', 27, 4, 2.0, 'fwd', 'hybrid', 33, 'kia', 'optima', 'a', 2016, 'https://cdn.imagin.studio/getImage?make=kia&modelFamily=optima&year=2016&angle=front', 'Aarhus'),
(20, 'luxury sedan', 23, 6, 3.0, 'awd', 'gas', 28, 'audi', 'a6', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=audi&modelFamily=a6&year=2021&angle=front', 'Odense'),
(31, 'compact car', 34, 3, 1.5, 'fwd', 'gas', 41, 'mini', 'cooper', 'm', 2019, 'https://cdn.imagin.studio/getImage?make=mini&modelFamily=cooper&year=2019&angle=front', 'Copenhagen'),
(33, 'electric', 118, 0, 0.0, 'rwd', 'electric', 113, 'tesla', 'model 3', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=tesla&modelFamily=model3&year=2021&angle=front', 'Aarhus'),
(16, 'muscle car', 19, 8, 5.7, 'rwd', 'gas', 25, 'dodge', 'challenger', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=dodge&modelFamily=challenger&year=2018&angle=front', 'Odense'),
(29, 'compact suv', 32, 4, 2.0, 'awd', 'gas', 35, 'subaru', 'forester', 'cvt', 2020, 'https://cdn.imagin.studio/getImage?make=subaru&modelFamily=forester&year=2020&angle=front', 'Copenhagen'),
(25, 'wagon', 28, 4, 2.0, 'awd', 'gas', 33, 'volvo', 'v60', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=volvo&modelFamily=v60&year=2019&angle=front', 'Aarhus'),
(28, 'compact suv', 31, 4, 1.5, 'fwd', 'gas', 34, 'chevrolet', 'equinox', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=chevrolet&modelFamily=equinox&year=2018&angle=front', 'Odense'),
(19, 'suv', 22, 6, 3.5, 'awd', 'gas', 27, 'nissan', 'pathfinder', 'cvt', 2020, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=pathfinder&year=2020&angle=front', 'Copenhagen'),
(27, 'sedan', 30, 4, 2.0, 'fwd', 'gas', 36, 'volkswagen', 'jetta', 'm', 2017, 'https://cdn.imagin.studio/getImage?make=volkswagen&modelFamily=jetta&year=2017&angle=front', 'Aarhus'),
(23, 'sports car', 25, 6, 3.7, 'rwd', 'gas', 28, 'nissan', '370z', 'm', 2019, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=370z&year=2019&angle=front', 'Odense'),
(24, 'luxury sedan', 27, 4, 2.0, 'rwd', 'gas', 32, 'mercedes-benz', 'c-class', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=mercedes-benz&modelFamily=c-class&year=2020&angle=front', 'Copenhagen'),
(26, 'compact suv', 29, 4, 1.5, 'awd', 'gas', 33, 'honda', 'cr-v', 'cvt', 2021, 'https://cdn.imagin.studio/getImage?make=honda&modelFamily=cr-v&year=2021&angle=front', 'Aarhus'),
(18, 'midsize car', 21, 4, 2.2, 'fwd', 'gas', 26, 'toyota', 'camry', 'a', 1993, 'https://cdn.imagin.studio/getImage?make=toyota&modelFamily=camry&year=1993&angle=front', 'Copenhagen'),
(27, 'compact car', 30, 4, 1.8, 'fwd', 'gas', 36, 'honda', 'civic', 'm', 2018, 'https://cdn.imagin.studio/getImage?make=honda&modelFamily=civic&year=2018&angle=front', 'Aarhus'),
(23, 'suv', 26, 4, 2.5, 'awd', 'gas', 31, 'toyota', 'rav4', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=toyota&modelFamily=rav4&year=2020&angle=front', 'Odense'),
(21, 'pickup truck', 24, 6, 3.3, 'rwd', 'gas', 28, 'ford', 'f-150', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=ford&modelFamily=f-150&year=2019&angle=front', 'Copenhagen'),
(30, 'compact car', 33, 4, 2.0, 'fwd', 'gas', 40, 'mazda', 'mazda3', 'm', 2021, 'https://cdn.imagin.studio/getImage?make=mazda&modelFamily=mazda3&year=2021&angle=front', 'Aarhus'),
(22, 'luxury suv', 25, 6, 3.0, 'awd', 'gas', 29, 'bmw', 'x5', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=bmw&modelFamily=x5&year=2020&angle=front', 'Odense'),
(28, 'hatchback', 32, 4, 1.6, 'fwd', 'gas', 38, 'hyundai', 'elantra', 'a', 2017, 'https://cdn.imagin.studio/getImage?make=hyundai&modelFamily=elantra&year=2017&angle=front', 'Copenhagen'),
(24, 'sedan', 27, 4, 2.0, 'fwd', 'hybrid', 33, 'kia', 'optima', 'a', 2016, 'https://cdn.imagin.studio/getImage?make=kia&modelFamily=optima&year=2016&angle=front', 'Aarhus'),
(20, 'luxury sedan', 23, 6, 3.0, 'awd', 'gas', 28, 'audi', 'a6', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=audi&modelFamily=a6&year=2021&angle=front', 'Odense'),
(31, 'compact car', 34, 3, 1.5, 'fwd', 'gas', 41, 'mini', 'cooper', 'm', 2019, 'https://cdn.imagin.studio/getImage?make=mini&modelFamily=cooper&year=2019&angle=front', 'Copenhagen'),
(33, 'electric', 118, 0, 0.0, 'rwd', 'electric', 113, 'tesla', 'model 3', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=tesla&modelFamily=model3&year=2021&angle=front', 'Aarhus'),
(16, 'muscle car', 19, 8, 5.7, 'rwd', 'gas', 25, 'dodge', 'challenger', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=dodge&modelFamily=challenger&year=2018&angle=front', 'Odense'),
(29, 'compact suv', 32, 4, 2.0, 'awd', 'gas', 35, 'subaru', 'forester', 'cvt', 2020, 'https://cdn.imagin.studio/getImage?make=subaru&modelFamily=forester&year=2020&angle=front', 'Copenhagen'),
(25, 'wagon', 28, 4, 2.0, 'awd', 'gas', 33, 'volvo', 'v60', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=volvo&modelFamily=v60&year=2019&angle=front', 'Aarhus'),
(28, 'compact suv', 31, 4, 1.5, 'fwd', 'gas', 34, 'chevrolet', 'equinox', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=chevrolet&modelFamily=equinox&year=2018&angle=front', 'Odense'),
(19, 'suv', 22, 6, 3.5, 'awd', 'gas', 27, 'nissan', 'pathfinder', 'cvt', 2020, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=pathfinder&year=2020&angle=front', 'Copenhagen'),
(27, 'sedan', 30, 4, 2.0, 'fwd', 'gas', 36, 'volkswagen', 'jetta', 'm', 2017, 'https://cdn.imagin.studio/getImage?make=volkswagen&modelFamily=jetta&year=2017&angle=front', 'Aarhus'),
(23, 'sports car', 25, 6, 3.7, 'rwd', 'gas', 28, 'nissan', '370z', 'm', 2019, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=370z&year=2019&angle=front', 'Odense'),
(24, 'luxury sedan', 27, 4, 2.0, 'rwd', 'gas', 32, 'mercedes-benz', 'c-class', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=mercedes-benz&modelFamily=c-class&year=2020&angle=front', 'Copenhagen'),
(26, 'compact suv', 29, 4, 1.5, 'awd', 'gas', 33, 'honda', 'cr-v', 'cvt', 2021, 'https://cdn.imagin.studio/getImage?make=honda&modelFamily=cr-v&year=2021&angle=front', 'Aarhus'),
(22, 'sedan', 25, 4, 2.4, 'fwd', 'gas', 30, 'toyota', 'corolla', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=toyota&modelFamily=corolla&year=2019&angle=front', 'Copenhagen'),
(29, 'hatchback', 32, 4, 1.6, 'fwd', 'gas', 37, 'volkswagen', 'golf', 'm', 2020, 'https://cdn.imagin.studio/getImage?make=volkswagen&modelFamily=golf&year=2020&angle=front', 'Odense'),
(25, 'sedan', 28, 4, 2.5, 'fwd', 'gas', 34, 'nissan', 'altima', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=altima&year=2018&angle=front', 'Aarhus'),
(20, 'suv', 23, 6, 3.6, 'awd', 'gas', 28, 'jeep', 'grand cherokee', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=jeep&modelFamily=grand-cherokee&year=2019&angle=front', 'Copenhagen'),
(27, 'compact car', 31, 4, 2.0, 'fwd', 'gas', 38, 'hyundai', 'accent', 'm', 2017, 'https://cdn.imagin.studio/getImage?make=hyundai&modelFamily=accent&year=2017&angle=front', 'Odense'),
(21, 'luxury sedan', 24, 6, 3.5, 'awd', 'gas', 29, 'lexus', 'es', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=lexus&modelFamily=es&year=2021&angle=front', 'Aarhus'),
(30, 'compact car', 34, 4, 1.8, 'fwd', 'gas', 40, 'toyota', 'prius', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=toyota&modelFamily=prius&year=2020&angle=front', 'Copenhagen'),
(18, 'pickup truck', 21, 8, 5.3, 'rwd', 'gas', 26, 'chevrolet', 'silverado', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=chevrolet&modelFamily=silverado&year=2018&angle=front', 'Odense'),
(26, 'suv', 29, 4, 2.0, 'awd', 'gas', 34, 'mazda', 'cx-5', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=mazda&modelFamily=cx-5&year=2021&angle=front', 'Aarhus'),
(23, 'sedan', 26, 4, 2.5, 'fwd', 'gas', 32, 'honda', 'accord', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=honda&modelFamily=accord&year=2019&angle=front', 'Copenhagen'),
(28, 'compact suv', 32, 4, 1.5, 'fwd', 'gas', 38, 'kia', 'sportage', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=kia&modelFamily=sportage&year=2020&angle=front', 'Odense'),
(19, 'luxury suv', 22, 8, 4.4, 'awd', 'gas', 27, 'audi', 'q7', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=audi&modelFamily=q7&year=2019&angle=front', 'Aarhus'),
(32, 'electric', 120, 0, 0.0, 'awd', 'electric', 115, 'tesla', 'model y', 'a', 2022, 'https://cdn.imagin.studio/getImage?make=tesla&modelFamily=modely&year=2022&angle=front', 'Copenhagen'),
(24, 'sedan', 27, 4, 2.0, 'fwd', 'gas', 33, 'ford', 'fusion', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=ford&modelFamily=fusion&year=2018&angle=front', 'Odense'),
(17, 'sports car', 20, 8, 5.0, 'rwd', 'gas', 25, 'ford', 'mustang', 'm', 2020, 'https://cdn.imagin.studio/getImage?make=ford&modelFamily=mustang&year=2020&angle=front', 'Aarhus'),
(25, 'compact suv', 28, 4, 2.0, 'awd', 'gas', 33, 'toyota', 'c-hr', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=toyota&modelFamily=c-hr&year=2019&angle=front', 'Copenhagen'),
(29, 'hatchback', 33, 4, 1.4, 'fwd', 'gas', 39, 'ford', 'fiesta', 'm', 2017, 'https://cdn.imagin.studio/getImage?make=ford&modelFamily=fiesta&year=2017&angle=front', 'Odense'),
(21, 'luxury sedan', 24, 6, 3.0, 'awd', 'gas', 29, 'bmw', '5 series', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=bmw&modelFamily=5-series&year=2020&angle=front', 'Aarhus'),
(27, 'sedan', 30, 4, 2.0, 'fwd', 'gas', 36, 'chevrolet', 'malibu', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=chevrolet&modelFamily=malibu&year=2019&angle=front', 'Copenhagen'),
(20, 'suv', 23, 6, 3.5, 'awd', 'gas', 28, 'honda', 'pilot', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=honda&modelFamily=pilot&year=2020&angle=front', 'Odense'),
(26, 'compact car', 30, 4, 2.0, 'fwd', 'gas', 37, 'kia', 'forte', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=kia&modelFamily=forte&year=2018&angle=front', 'Aarhus'),
(22, 'sedan', 25, 4, 2.5, 'fwd', 'gas', 31, 'subaru', 'legacy', 'cvt', 2019, 'https://cdn.imagin.studio/getImage?make=subaru&modelFamily=legacy&year=2019&angle=front', 'Copenhagen'),
(31, 'compact car', 35, 4, 1.6, 'fwd', 'gas', 42, 'hyundai', 'venue', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=hyundai&modelFamily=venue&year=2021&angle=front', 'Odense'),
(18, 'pickup truck', 21, 8, 5.7, 'rwd', 'gas', 26, 'ram', '1500', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=ram&modelFamily=1500&year=2019&angle=front', 'Aarhus'),
(28, 'compact suv', 32, 4, 1.5, 'fwd', 'gas', 38, 'nissan', 'rogue', 'cvt', 2020, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=rogue&year=2020&angle=front', 'Copenhagen'),
(23, 'luxury sedan', 26, 4, 2.0, 'rwd', 'gas', 31, 'mercedes-benz', 'e-class', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=mercedes-benz&modelFamily=e-class&year=2021&angle=front', 'Odense'),
(25, 'sedan', 28, 4, 2.0, 'fwd', 'gas', 34, 'mazda', 'mazda6', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=mazda&modelFamily=mazda6&year=2018&angle=front', 'Aarhus'),
(19, 'suv', 22, 6, 3.6, 'awd', 'gas', 27, 'volkswagen', 'atlas', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=volkswagen&modelFamily=atlas&year=2020&angle=front', 'Copenhagen'),
(30, 'hatchback', 34, 4, 1.5, 'fwd', 'gas', 40, 'mazda', 'mazda2', 'm', 2019, 'https://cdn.imagin.studio/getImage?make=mazda&modelFamily=mazda2&year=2019&angle=front', 'Odense'),
(24, 'compact suv', 27, 4, 2.5, 'awd', 'gas', 33, 'nissan', 'murano', 'cvt', 2019, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=murano&year=2019&angle=front', 'Aarhus'),
(21, 'luxury suv', 24, 6, 3.0, 'awd', 'gas', 29, 'mercedes-benz', 'glc', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=mercedes-benz&modelFamily=glc&year=2020&angle=front', 'Copenhagen'),
(27, 'sedan', 31, 4, 2.0, 'fwd', 'gas', 38, 'volkswagen', 'passat', 'a', 2017, 'https://cdn.imagin.studio/getImage?make=volkswagen&modelFamily=passat&year=2017&angle=front', 'Odense'),
(33, 'electric', 125, 0, 0.0, 'rwd', 'electric', 120, 'nissan', 'leaf', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=leaf&year=2021&angle=front', 'Aarhus'),
(22, 'sedan', 25, 4, 2.4, 'fwd', 'gas', 30, 'chrysler', '300', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=chrysler&modelFamily=300&year=2018&angle=front', 'Copenhagen'),
(26, 'compact suv', 29, 4, 1.5, 'awd', 'gas', 34, 'jeep', 'compass', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=jeep&modelFamily=compass&year=2020&angle=front', 'Odense'),
(20, 'luxury sedan', 23, 6, 3.5, 'awd', 'gas', 28, 'infiniti', 'q50', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=infiniti&modelFamily=q50&year=2019&angle=front', 'Aarhus'),
(28, 'hatchback', 32, 4, 1.6, 'fwd', 'gas', 38, 'kia', 'rio', 'm', 2018, 'https://cdn.imagin.studio/getImage?make=kia&modelFamily=rio&year=2018&angle=front', 'Copenhagen'),
(23, 'suv', 26, 4, 2.5, 'awd', 'gas', 31, 'subaru', 'outback', 'cvt', 2020, 'https://cdn.imagin.studio/getImage?make=subaru&modelFamily=outback&year=2020&angle=front', 'Odense'),
(31, 'compact car', 35, 4, 1.5, 'fwd', 'gas', 42, 'chevrolet', 'spark', 'm', 2019, 'https://cdn.imagin.studio/getImage?make=chevrolet&modelFamily=spark&year=2019&angle=front', 'Aarhus'),
(19, 'pickup truck', 22, 8, 6.2, 'rwd', 'gas', 27, 'ford', 'f-250', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=ford&modelFamily=f-250&year=2020&angle=front', 'Copenhagen'),
(25, 'sedan', 28, 4, 2.0, 'fwd', 'gas', 34, 'acura', 'tlx', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=acura&modelFamily=tlx&year=2019&angle=front', 'Odense'),
(29, 'compact suv', 33, 4, 2.0, 'awd', 'gas', 39, 'hyundai', 'tucson', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=hyundai&modelFamily=tucson&year=2021&angle=front', 'Aarhus'),
(21, 'luxury suv', 24, 6, 3.0, 'awd', 'gas', 29, 'lexus', 'rx', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=lexus&modelFamily=rx&year=2020&angle=front', 'Copenhagen'),
(27, 'sedan', 30, 4, 2.0, 'fwd', 'gas', 36, 'buick', 'regal', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=buick&modelFamily=regal&year=2018&angle=front', 'Odense'),
(24, 'compact car', 27, 4, 2.0, 'fwd', 'gas', 33, 'dodge', 'dart', 'm', 2016, 'https://cdn.imagin.studio/getImage?make=dodge&modelFamily=dart&year=2016&angle=front', 'Aarhus'),
(18, 'sports car', 21, 8, 6.2, 'rwd', 'gas', 26, 'chevrolet', 'camaro', 'm', 2019, 'https://cdn.imagin.studio/getImage?make=chevrolet&modelFamily=camaro&year=2019&angle=front', 'Copenhagen'),
(26, 'suv', 29, 4, 2.5, 'awd', 'gas', 34, 'ford', 'escape', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=ford&modelFamily=escape&year=2020&angle=front', 'Odense'),
(30, 'hatchback', 34, 4, 1.4, 'fwd', 'gas', 40, 'chevrolet', 'sonic', 'a', 2017, 'https://cdn.imagin.studio/getImage?make=chevrolet&modelFamily=sonic&year=2017&angle=front', 'Aarhus'),
(22, 'sedan', 25, 4, 2.4, 'fwd', 'gas', 30, 'mitsubishi', 'lancer', 'a', 2016, 'https://cdn.imagin.studio/getImage?make=mitsubishi&modelFamily=lancer&year=2016&angle=front', 'Copenhagen'),
(28, 'compact suv', 32, 4, 1.5, 'fwd', 'gas', 38, 'mitsubishi', 'outlander', 'cvt', 2019, 'https://cdn.imagin.studio/getImage?make=mitsubishi&modelFamily=outlander&year=2019&angle=front', 'Odense'),
(20, 'luxury sedan', 23, 6, 3.0, 'awd', 'gas', 28, 'cadillac', 'ct5', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=cadillac&modelFamily=ct5&year=2020&angle=front', 'Aarhus'),
(25, 'sedan', 28, 4, 2.0, 'fwd', 'gas', 34, 'lincoln', 'mkz', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=lincoln&modelFamily=mkz&year=2019&angle=front', 'Copenhagen'),
(31, 'compact car', 35, 4, 1.6, 'fwd', 'gas', 42, 'nissan', 'versa', 'm', 2020, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=versa&year=2020&angle=front', 'Odense'),
(23, 'suv', 26, 6, 3.5, 'awd', 'gas', 31, 'acura', 'mdx', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=acura&modelFamily=mdx&year=2019&angle=front', 'Aarhus'),
(27, 'compact suv', 30, 4, 2.0, 'awd', 'gas', 36, 'buick', 'encore', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=buick&modelFamily=encore&year=2018&angle=front', 'Copenhagen'),
(19, 'pickup truck', 22, 8, 5.7, 'rwd', 'gas', 27, 'toyota', 'tundra', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=toyota&modelFamily=tundra&year=2019&angle=front', 'Odense'),
(34, 'electric', 130, 0, 0.0, 'awd', 'electric', 125, 'tesla', 'model x', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=tesla&modelFamily=modelx&year=2021&angle=front', 'Aarhus'),
(24, 'sedan', 27, 4, 2.5, 'fwd', 'gas', 33, 'toyota', 'avalon', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=toyota&modelFamily=avalon&year=2018&angle=front', 'Copenhagen'),
(21, 'luxury suv', 24, 6, 3.6, 'awd', 'gas', 29, 'cadillac', 'xt5', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=cadillac&modelFamily=xt5&year=2020&angle=front', 'Odense'),
(26, 'compact car', 29, 4, 2.0, 'fwd', 'gas', 35, 'ford', 'focus', 'a', 2017, 'https://cdn.imagin.studio/getImage?make=ford&modelFamily=focus&year=2017&angle=front', 'Aarhus'),
(22, 'suv', 25, 6, 3.5, 'awd', 'gas', 30, 'infiniti', 'qx60', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=infiniti&modelFamily=qx60&year=2019&angle=front', 'Copenhagen'),
(29, 'hatchback', 33, 4, 1.5, 'fwd', 'gas', 39, 'honda', 'fit', 'm', 2018, 'https://cdn.imagin.studio/getImage?make=honda&modelFamily=fit&year=2018&angle=front', 'Odense'),
(20, 'luxury sedan', 23, 6, 3.5, 'awd', 'gas', 28, 'genesis', 'g80', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=genesis&modelFamily=g80&year=2021&angle=front', 'Aarhus'),
(28, 'compact suv', 32, 4, 1.6, 'fwd', 'gas', 38, 'kia', 'seltos', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=kia&modelFamily=seltos&year=2021&angle=front', 'Copenhagen'),
(25, 'sedan', 28, 4, 2.0, 'fwd', 'gas', 34, 'volkswagen', 'arteon', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=volkswagen&modelFamily=arteon&year=2020&angle=front', 'Odense'),
(17, 'sports car', 20, 8, 5.2, 'rwd', 'gas', 25, 'audi', 'r8', 'm', 2020, 'https://cdn.imagin.studio/getImage?make=audi&modelFamily=r8&year=2020&angle=front', 'Aarhus'),
(23, 'suv', 26, 4, 2.5, 'awd', 'gas', 31, 'kia', 'sorento', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=kia&modelFamily=sorento&year=2019&angle=front', 'Copenhagen'),
(30, 'compact car', 34, 4, 1.8, 'fwd', 'gas', 40, 'chevrolet', 'cruze', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=chevrolet&modelFamily=cruze&year=2018&angle=front', 'Odense'),
(21, 'luxury sedan', 24, 6, 3.0, 'awd', 'gas', 29, 'volvo', 's90', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=volvo&modelFamily=s90&year=2020&angle=front', 'Aarhus'),
(27, 'compact suv', 31, 4, 2.0, 'awd', 'gas', 37, 'volvo', 'xc40', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=volvo&modelFamily=xc40&year=2021&angle=front', 'Copenhagen'),
(19, 'pickup truck', 22, 8, 6.7, 'rwd', 'diesel', 27, 'ram', '2500', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=ram&modelFamily=2500&year=2020&angle=front', 'Odense'),
(26, 'sedan', 29, 4, 2.0, 'fwd', 'gas', 35, 'hyundai', 'sonata', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=hyundai&modelFamily=sonata&year=2020&angle=front', 'Aarhus'),
(24, 'suv', 27, 6, 3.6, 'awd', 'gas', 32, 'gmc', 'acadia', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=gmc&modelFamily=acadia&year=2019&angle=front', 'Copenhagen'),
(31, 'hatchback', 35, 4, 1.4, 'fwd', 'gas', 41, 'fiat', '500', 'm', 2017, 'https://cdn.imagin.studio/getImage?make=fiat&modelFamily=500&year=2017&angle=front', 'Odense'),
(22, 'luxury suv', 25, 6, 3.0, 'awd', 'gas', 30, 'lincoln', 'aviator', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=lincoln&modelFamily=aviator&year=2020&angle=front', 'Aarhus'),
(28, 'compact car', 32, 4, 1.8, 'fwd', 'gas', 38, 'mitsubishi', 'mirage', 'm', 2019, 'https://cdn.imagin.studio/getImage?make=mitsubishi&modelFamily=mirage&year=2019&angle=front', 'Copenhagen'),
(35, 'electric', 135, 0, 0.0, 'awd', 'electric', 130, 'audi', 'e-tron', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=audi&modelFamily=e-tron&year=2021&angle=front', 'Odense'),
(20, 'sports car', 23, 6, 3.0, 'rwd', 'gas', 28, 'bmw', 'z4', 'm', 2020, 'https://cdn.imagin.studio/getImage?make=bmw&modelFamily=z4&year=2020&angle=front', 'Aarhus'),
(25, 'sedan', 28, 4, 2.5, 'fwd', 'gas', 34, 'nissan', 'maxima', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=maxima&year=2019&angle=front', 'Copenhagen'),
(23, 'suv', 26, 6, 3.5, 'awd', 'gas', 31, 'toyota', 'highlander', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=toyota&modelFamily=highlander&year=2020&angle=front', 'Odense'),
(29, 'compact suv', 33, 4, 2.0, 'awd', 'gas', 39, 'gmc', 'terrain', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=gmc&modelFamily=terrain&year=2019&angle=front', 'Aarhus'),
(21, 'luxury sedan', 24, 6, 3.0, 'awd', 'gas', 29, 'jaguar', 'xf', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=jaguar&modelFamily=xf&year=2020&angle=front', 'Copenhagen'),
(27, 'hatchback', 31, 4, 1.6, 'fwd', 'gas', 37, 'toyota', 'yaris', 'm', 2018, 'https://cdn.imagin.studio/getImage?make=toyota&modelFamily=yaris&year=2018&angle=front', 'Odense'),
(18, 'pickup truck', 21, 8, 5.0, 'rwd', 'gas', 26, 'nissan', 'titan', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=titan&year=2019&angle=front', 'Aarhus'),
(26, 'sedan', 29, 4, 2.0, 'fwd', 'gas', 35, 'genesis', 'g70', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=genesis&modelFamily=g70&year=2021&angle=front', 'Copenhagen'),
(24, 'suv', 27, 4, 2.5, 'awd', 'gas', 33, 'hyundai', 'santa fe', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=hyundai&modelFamily=santa-fe&year=2020&angle=front', 'Odense'),
(30, 'compact car', 34, 4, 1.5, 'fwd', 'gas', 40, 'honda', 'insight', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=honda&modelFamily=insight&year=2020&angle=front', 'Aarhus'),
(22, 'luxury suv', 25, 6, 3.0, 'awd', 'gas', 30, 'jaguar', 'f-pace', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=jaguar&modelFamily=f-pace&year=2020&angle=front', 'Copenhagen'),
(28, 'compact suv', 32, 4, 1.5, 'fwd', 'gas', 38, 'chevrolet', 'trax', 'a', 2018, 'https://cdn.imagin.studio/getImage?make=chevrolet&modelFamily=trax&year=2018&angle=front', 'Odense'),
(19, 'sports car', 22, 8, 6.2, 'rwd', 'gas', 27, 'chevrolet', 'corvette', 'm', 2020, 'https://cdn.imagin.studio/getImage?make=chevrolet&modelFamily=corvette&year=2020&angle=front', 'Aarhus'),
(25, 'sedan', 28, 4, 2.0, 'fwd', 'gas', 34, 'mazda', 'cx-30', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=mazda&modelFamily=cx-30&year=2021&angle=front', 'Copenhagen'),
(32, 'electric', 122, 0, 0.0, 'fwd', 'electric', 117, 'chevrolet', 'bolt', 'a', 2021, 'https://cdn.imagin.studio/getImage?make=chevrolet&modelFamily=bolt&year=2021&angle=front', 'Odense'),
(23, 'suv', 26, 6, 3.6, 'awd', 'gas', 31, 'dodge', 'durango', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=dodge&modelFamily=durango&year=2019&angle=front', 'Aarhus'),
(27, 'compact car', 31, 4, 2.0, 'fwd', 'gas', 38, 'subaru', 'impreza', 'cvt', 2020, 'https://cdn.imagin.studio/getImage?make=subaru&modelFamily=impreza&year=2020&angle=front', 'Copenhagen'),
(21, 'luxury sedan', 24, 6, 3.0, 'awd', 'gas', 29, 'alfa romeo', 'giulia', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=alfa-romeo&modelFamily=giulia&year=2020&angle=front', 'Odense'),
(29, 'hatchback', 33, 4, 1.4, 'fwd', 'gas', 39, 'nissan', 'sentra', 'a', 2020, 'https://cdn.imagin.studio/getImage?make=nissan&modelFamily=sentra&year=2020&angle=front', 'Aarhus'),
(20, 'pickup truck', 23, 8, 5.3, 'rwd', 'gas', 28, 'gmc', 'sierra', 'a', 2019, 'https://cdn.imagin.studio/getImage?make=gmc&modelFamily=sierra&year=2019&angle=front', 'Copenhagen');
